### ISSUE TITLE
Questions About Parameter Settings

### ISSUE THREAD

**Issue by zhengluohu** [FredericoMetelo/peersim-environment#4]
Hello, I encountered a few parameters that were not explained while setting parameters, and I don't understand their specific meaning and impact.

**LayerThatGetTasks**: Does this parameter determine which layers can receive tasks generated by the client? If so, does this parameter overlap with **clientLayers** and **ClientIsSelf**?

**ChannelTypes** and **ChannelTypesBetweenLaye**r: What do these parameters mean?

If I set the parameters as follows:

**nodes_per_laye**r=[6, 4],
**cloud_access**=[1, 1],
**freqs_per_layer**=[4e7, 2e7],
**no_cores_per_laye**r=[2, 1],
**layersThatGetTasks**=[0],
**clientLayers**=[0],
**clientIsSelf**=1

Does this mean that only the workers in layer 0 have a corresponding client, and these clients can only send generated tasks to the corresponding workers?

I look forward to your response.  Thank you.

**Comment by FredericoMetelo** [comment]
Hello!
Firstly, I must apologize. It seems I forgot to add their descriptions to the readme. I will be adding it shortly. But to answer your question:

LayersThatGetTasks is a new parameter I added to be able to define with a finer control what clients would be receiving tasks generated by the clients and those that don't. This means that all clients in layers that are not in the layers that get tasks would not get any tasks unless someone offloads to them.

Regarding the interaction with clientIsSelf and ChannelTypesBetweenLayer:
If clientIsSelf and a given client's layer is in layersThatGetTasks, then that client would be generating tasks for itself, all the clients in layers not in layersThatGetTasks would not receive any tasks. Layers that get tasks is a coma separated list of the layers id. IE if layers 0 and 1 get tasks then, in the configs, you would have:

layersThatGetTasks 0,1


ChannelTypesPerLayers and ChannelTypes, are parameters that help define what channel types would be available between different layer types. This is to permit having, for example, wireless between IoT devices and Fog Nodes, and a faster connection (IE wired) between Fog Nodes and the Cloud. The classes of the channel types to load are defined with the parameter ChannelTypes (Note: different channel types will ideally have different properties). The channel types are defined as a list of "," separated values.

You specify what channel type connects different layers with the ChannelTypesPerLayers. The ChannelTypesPerLayers is defined as a matrix of layers x layers (IE with dimensions NO_LAYERS x NO_LAYERS). You have the index of the channel type, in ChannelTypes, between layer i and j  in ChannelTypesPerLayers[i][j]. The channel types per layer is defined in the configs as with a string where values in a row are "," separated, and different rows are ";" separated.

channelTypesPerLayer PeersimSimulator.peersim.env.Transport.OpticalFiberSNR;PeersimSimulator.peersim.env.Transport.WirelessSNR
channelTypesBetweenLayers 0,0,1;0,0,1;1,1,1

Although adding the different channel types is still a work in progress. It has little overlap on who gets tasks, but can affect the delay that those that do get tasks directly from client's would receive them.


> Does this mean that only the workers in layer 0 have a corresponding client, and these clients can only send generated tasks to the corresponding workers?

This is correct.

**Comment by zhengluohu** [comment]
Thank you for your prompt and detailed reply. I now understand the purpose of these parameters. The settings are really meaningful and interesting！
